import Head from 'next/head';
import Image from 'next/image';
import SectionLayout from '../components/section-layout/section-layout';
import styles from '../styles/Home.module.css';
import siteContent from '../public/PublicVariables';
import DoubleContentLayout from '../components/section-layout/double-content-layout';

export default function Home() {
  const Titles = siteContent.sectionTitles;
  const Subtitles = siteContent.sectionSubtitles;
  const SectionImg = siteContent.sectionImages;
  return (
    <>
      <div className={styles.main}>
        <SectionLayout 
          title={Titles.title1} 
          subtitle={Subtitles.subtitle1}
          img={SectionImg.astronaut}
        ></SectionLayout>
        <DoubleContentLayout 
          title={Titles.title2}
          subtitle={Subtitles.subtitle2}
          item1={SectionImg.discover}
          item2={SectionImg.zoomCall}></DoubleContentLayout>
        <SectionLayout 
          title={Titles.title3}
          subtitle={Subtitles.subtitle3}
          img={SectionImg.path}></SectionLayout>
        <SectionLayout 
          title={Titles.title4}
          subtitle={Subtitles.subtitle4}></SectionLayout>
        <SectionLayout 
          title={Titles.title5}
          subtitle={Subtitles.subtitle5}></SectionLayout>
        <SectionLayout 
          title={Titles.title6}
          subtitle={Subtitles.subtitle6}></SectionLayout>
        <SectionLayout 
          title={Titles.title7}
          subtitle={Subtitles.subtitle7}></SectionLayout>
        <SectionLayout 
          title={Titles.title8}
          subtitle={Subtitles.subtitle8}></SectionLayout>
        <SectionLayout 
          title={Titles.title9}
          subtitle={Subtitles.subtitle9}></SectionLayout>
        <SectionLayout 
          title={Titles.title10}
          subtitle={Subtitles.subtitle10}></SectionLayout>
      </div>
      
    </>
  )
}
// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>TechFleet DAO</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
